#!/bin/bash
#
# Copyright 2019 Northern.tech AS
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

set -e

function usage() {
    echo "./$(basename $0) <report>"
    echo "  where <report> is the directory containing the test report."
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

REPORT=$1

IMAGE_NAME_SERVE=allure-report-server

docker build -t ${IMAGE_NAME_SERVE} --build-arg REPORT=$REPORT -f Dockerfile.serve .

echo "Serving website in localhost:80"
docker run \
       --network host \
       $IMAGE_NAME_SERVE
