#!/bin/bash
#
# Copyright 2019 Northern.tech AS
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

set -e

function usage() {
    echo "./$(basename $0) <prev-report> <results> <output-report>"
    echo "  where <prev-report> is the last generated report,"
    echo "  <results> is the current test results,"
    echo "  and <output-report> is where to copy the new report"
    echo "  Set <prev-report> to /dev/null for the very first report."
}

if [ -z "$3" ]; then
    usage
    exit 1
fi

PREV_REPORT=$1
RESULTS=$2
NEW_REPORT=$3

IMAGE_NAME_GENERATE=allure-report-generator

docker build -t ${IMAGE_NAME_GENERATE} .

mkdir -p $NEW_REPORT

docker run \
       --volume "$(realpath $PREV_REPORT):/prev-report" \
       --volume "$(realpath $RESULTS):/results" \
       --volume "$(realpath $NEW_REPORT):/report" \
       $IMAGE_NAME_GENERATE

sudo chown -R $(id -u):$(id -g) $NEW_REPORT

echo "Test report generated at $NEW_REPORT"
