
include:
  - project: 'Northern.tech/Mender/mender-gateway'
    file: '.gitlab-ci-build-package.yml'
    ref: 'master'

build:client:docker:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  only:
    variables:
      - $BUILD_CLIENT == "true"
  variables:
    DOCKER_BUILDKIT: 1
  needs:
    - init:workspace
  allow_failure: false
  image: docker
  services:
    - docker:dind
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt
    # Dependencies
    - apk --update add python3 py-pip curl jq bash git xz
    - wget https://raw.githubusercontent.com/mendersoftware/integration/master/extra/requirements.txt
    - pip3 install --break-system-packages -r requirements.txt
    # Post job status
    - source ${CI_PROJECT_DIR}/build_revisions.env
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
    # Prepare workspace
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
  script:
    - mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
    # First build mender's repo Docker image
    - docker_url=$($WORKSPACE/integration/extra/release_tool.py --map-name docker mender-client-docker docker_url)
    - cd go/src/github.com/mendersoftware/mender
    - ./tests/build-docker -t $docker_url:pr
    - docker save $docker_url:pr -o ${CI_PROJECT_DIR}/stage-artifacts/mender-client-docker.tar
    # Then, if available, build integration's repo Docker image (Mender 2.7 and later)
    - if $($WORKSPACE/integration/extra/release_tool.py -l docker | egrep -q '^mender-client-docker-addons$'); then
    -   docker_url=$($WORKSPACE/integration/extra/release_tool.py --map-name docker mender-client-docker-addons docker_url)
    -   cd $WORKSPACE/integration/extra/mender-client-docker-addons
    -   docker build
        --build-arg MENDER_CLIENT_REV=$MENDER_REV
        --build-arg MENDER_CONNECT_REV=$MENDER_CONNECT_REV
        --build-arg MENDER_SETUP_REV=$MENDER_SETUP_REV
        --tag $docker_url:pr
        .
    -   mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
    -   docker save $docker_url:pr -o ${CI_PROJECT_DIR}/stage-artifacts/mender-client-docker-addons.tar
    - fi
    - echo "success" > /JOB_RESULT.txt
  after_script:
    - ls -lh stage-artifacts/
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    expire_in: 2w
    paths:
      - stage-artifacts/

build:servers:
  tags:
    - mender-qa-worker-generic-heavy
  stage: build
  only:
    variables:
      - $BUILD_SERVERS == "true"
      - $RUN_BACKEND_INTEGRATION_TESTS == "true"
      - $RUN_INTEGRATION_TESTS == "true"
  variables:
    DOCKER_BUILDKIT: 1
    ROLE_ARN: "arn:aws:iam::175683096866:role/nt-cicd-mender-binary-delta-ro"
  needs:
    - init:workspace
  allow_failure: false
  image: docker
  services:
    - docker:dind
  id_tokens:
    AWS_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt
    # Dependencies
    - apk --update --no-cache add bash git make python3 py-pip curl jq xz aws-cli
    - wget https://raw.githubusercontent.com/mendersoftware/integration/master/extra/requirements.txt
    - pip3 install --break-system-packages -r requirements.txt
    # Post job status
    - source ${CI_PROJECT_DIR}/build_revisions.env
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
    # Prepare workspace
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
    # Gitlab AWS OIDC mapping auth
    # To get s3://mender-binaries/mender-binary-delta objects
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${AWS_OIDC_TOKEN}
      --duration-seconds ${AWS_OIDC_TOKEN_TIMEOUT:-3600}
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
  script:
    - ${WORKSPACE}/mender-qa/scripts/servers-build.sh
    - echo "success" > /JOB_RESULT.txt
  after_script:
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - if [ "$(cat /JOB_RESULT.txt)" != "success" ]; then ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"; fi

    - mkdir -p stage-artifacts
    - for image in $(${CI_PROJECT_DIR}/../integration/extra/release_tool.py -l docker); do
    -   if ! echo $image | egrep -q 'mender-client|mender-qemu|mender-monitor|mender-gateway-qemu-commercial'; then
    -     docker_url=$(${CI_PROJECT_DIR}/../integration/extra/release_tool.py --map-name docker $image docker_url)
    -     docker save $docker_url:pr -o stage-artifacts/${image}.tar
    -   fi
    - done

    - ls -lh stage-artifacts/
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    expire_in: 2w
    paths:
      - stage-artifacts/

build:mender-cli:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  only:
    variables:
      - $BUILD_SERVERS == "true"
      - $RUN_BACKEND_INTEGRATION_TESTS == "true"
      - $RUN_INTEGRATION_TESTS == "true"
  image: golang:1.20-alpine3.18
  needs:
    - init:workspace
  allow_failure: false
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt

    # Restore workspace from init stage
    - apk --update add xz
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz build_revisions.env /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
    - mv /tmp/build_revisions.env .
    # Export GOPATH
    - export GOPATH="$WORKSPACE/go"

    - apk --update add jq make curl git

    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

    # cd into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-cli
  script:
    - if grep -q build-multiplatform Makefile; then
        make build-multiplatform;
      else
        make build;
      fi
    - mkdir -p $CI_PROJECT_DIR/stage-artifacts
    - cp mender-cli* $CI_PROJECT_DIR/stage-artifacts

    # Always keep this at the end of the script stage
    - echo "success" > /JOB_RESULT.txt

  after_script:
    - ls -lh stage-artifacts/
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    paths:
      - stage-artifacts/

build:mender-artifact:
  tags:
    - mender-qa-worker-generic
  stage: build
  only:
    variables:
      - $BUILD_CLIENT == "true"
      - $RUN_BACKEND_INTEGRATION_TESTS == "true"
      - $RUN_INTEGRATION_TESTS == "true"
  variables:
    DOCKER_BUILDKIT: 1
  image: docker
  services:
    - docker:dind
  needs:
    - init:workspace
  allow_failure: false
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt

    # Check correct dind setup
    - docker version
    # Install dependencies
    - apk --update add bash curl git make jq xz
    # Restore workspace from init stage
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz build_revisions.env /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
    - mv /tmp/build_revisions.env .

    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

    # cd into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-artifact
  script:
    - make build-natives-contained
    - mkdir -p $CI_PROJECT_DIR/stage-artifacts
    - cp mender-artifact-* $CI_PROJECT_DIR/stage-artifacts

    # Always keep this at the end of the script stage
    - echo "success" > /JOB_RESULT.txt

  after_script:
    - ls -lh stage-artifacts/
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    expire_in: 2w
    paths:
      - stage-artifacts/

build:mender-monitor:package:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  image: alpine:3.12
  needs: []
  allow_failure: false
  before_script:
    - apk add --no-cache git openssh
    # Prepare SSH keys
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    # Clone monitor-client
    - git clone git@github.com:mendersoftware/monitor-client monitor-client
    - cd monitor-client
    - ( git fetch -u -f origin $MONITOR_CLIENT_REV:pr &&
          git checkout pr ||
          git checkout -f -b pr $MONITOR_CLIENT_REV
      ) || return 1
  script:
    - apk add --no-cache make git
    - git fetch --tags origin
    - make package
    - mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
    - mv mender-monitor-*.tar.gz ${CI_PROJECT_DIR}/stage-artifacts
    - ls -lh ${CI_PROJECT_DIR}/stage-artifacts/
  artifacts:
    paths:
      - stage-artifacts

build:mender-gateway:package:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  needs:
    - init:workspace
  allow_failure: false
  before_script:
    # Early exit when building an integration version without mender-gateway
    - apt update && apt install -yyq xz-utils
    - xz -d workspace.tar.xz
    - tar -tf workspace.tar
        ./go/src/github.com/mendersoftware/mender-gateway  >/dev/null 2>/dev/null || exit 0
    # Restore workspace from init stage
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar build_revisions.env /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - tar -xf /tmp/workspace.tar
    - mv /tmp/build_revisions.env .
    # Move into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-gateway
