# Repos to build are already checked out in init:workspace
# Reusable workspace restoration script template
.workspace_restore: &workspace_restore |
  apt-get update -yyq && apt-get install -yyq xz-utils
  WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
  tar -xf workspace.tar.xz -C ${WORKSPACE} ./go/src/github.com/mendersoftware/${COMPONENT_NAME}
  cd ${WORKSPACE}/go/src/github.com/mendersoftware/${COMPONENT_NAME}

include:
  # mender-gateway
  - component: gitlab.com/Northern.tech/Mender/mender-gateway/build-mender-gateway@master
    inputs:
      job_name: build:mender-gateway
      before_script:
        - *workspace_restore
      rules:
        - if: $MENDER_GATEWAY_REV != "latest"
  # mender-orchestrator
  - component: gitlab.com/Northern.tech/Mender/mender-orchestrator/build-mender-orchestrator@main
    inputs:
      job_name: build:mender-orchestrator
      architectures:
        - x86_64
        - arm
      before_script:
        - *workspace_restore
      rules:
        - if: $MENDER_ORCHESTRATOR_REV != "latest"
  # mender-binary-delta
  - component: gitlab.com/Northern.tech/Mender/mender-binary-delta/build-mender-binary-delta@master
    inputs:
      job_name: build:mender-binary-delta
      before_script:
        - *workspace_restore
      architectures:
        - x86_64
        - arm
      rules:
        # mender-binary-delta is not an independent component (subcomponent of Mender Client LTS).
        # We build it as long as neither the mender-binary-delta nor the mender revision is set to latest
        - if: $MENDER_BINARY_DELTA_REV != "latest" || $MENDER_REV != "latest"
  # mender-monitor
  - component: gitlab.com/Northern.tech/Mender/monitor-client/build-mender-monitor@master
    inputs:
      job_name: build:mender-monitor
      before_script:
        - *workspace_restore
      rules:
        # mender-monitor is not an independent component (subcomponent of Mender Client LTS).
        # We build it as long as neither the monitor-client nor the mender revision is set to latest
        - if: $MONITOR_CLIENT_REV != "latest" || $MENDER_REV != "latest"

build:client:docker:
  tags:
    - hetzner-amd-beefy
  stage: build
  only:
    variables:
      - $BUILD_CLIENT == "true"
  variables:
    DOCKER_BUILDKIT: 1
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1
    DOCKER_VERSION: "27.3"
  needs:
    - init:workspace
  allow_failure: false
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}-dind
      alias: docker
  before_script:
  before_script:
    # Restore workspace from init stage
    - apt update && apt install -yyq xz-utils
    - xz -d workspace.tar.xz
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - tar -xf /tmp/workspace.tar
    # Move into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-client-subcomponents
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt
    # Dependencies
    - apk --update add curl jq
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - cd virtual-device
    # QA-1176 TODO: move the "latest to tag" translation to the Dockerfile
    - |
      get_latest_tag() {
        git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' --refs $1 |
          grep -E 'v?[0-9]+\.[0-9]+\.[0-9]+.*$' |
          tail -n1 |
          cut -d'/' -f3
      }
    - if [ "$MENDER_REV" = "latest" ]; then
    -   MENDER_REV=$(get_latest_tag https://github.com/mendersoftware/mender.git)
    - fi
    - if [ "$MENDER_CONNECT_REV" = "latest" ]; then
    -   MENDER_CONNECT_REV=$(get_latest_tag https://github.com/mendersoftware/mender-connect.git)
    - fi
    - docker build
      --build-arg MENDER_CLIENT_REV=$MENDER_REV
      --build-arg MENDER_CONNECT_REV=$MENDER_CONNECT_REV
      --tag ${GITLAB_REGISTRY_PREFIX}-mender-client-docker-addons
      --push
      .
    - echo "success" > /JOB_RESULT.txt
  after_script:
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

