
include:
  - project: 'Northern.tech/Mender/mender-gateway'
    file: '.gitlab-ci-build-package.yml'
    ref: 'master'

build:client:docker:
  tags:
    - hetzner-amd-beefy
  stage: build
  only:
    variables:
      - $BUILD_CLIENT == "true"
  variables:
    DOCKER_BUILDKIT: 1
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1
    DOCKER_VERSION: "27.3"
  needs:
    - init:workspace
  allow_failure: false
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}-dind
      alias: docker
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt
    # Dependencies
    - apk --update add python3 py-pip curl jq bash git xz
    - wget https://raw.githubusercontent.com/mendersoftware/integration/master/extra/requirements.txt
    - pip3 install --break-system-packages -r requirements.txt
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
    # Prepare workspace
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    # First build mender's repo Docker image
    - cd go/src/github.com/mendersoftware/mender
    - ./tests/build-docker -t ${GITLAB_REGISTRY_PREFIX}-mender-client-docker --no-cache
    - docker push ${GITLAB_REGISTRY_PREFIX}-mender-client-docker
    - cd $WORKSPACE/integration/extra/mender-client-docker-addons
    - docker build
      --no-cache
      --build-arg MENDER_CLIENT_REV=$MENDER_REV
      --build-arg MENDER_CONNECT_REV=$MENDER_CONNECT_REV
      --build-arg MENDER_SETUP_REV=$MENDER_SETUP_REV
      --tag ${GITLAB_REGISTRY_PREFIX}-mender-client-docker-addons
      --push
      .
    - echo "success" > /JOB_RESULT.txt
  after_script:
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

build:mender-monitor:package:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  image: alpine:3.12
  needs: []
  allow_failure: false
  before_script:
    - apk add --no-cache git openssh
    # Prepare SSH keys
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    # Clone monitor-client
    - git clone git@github.com:mendersoftware/monitor-client monitor-client
    - cd monitor-client
    - ( git fetch -u -f origin $MONITOR_CLIENT_REV:pr &&
          git checkout pr ||
          git checkout -f -b pr $MONITOR_CLIENT_REV
      ) || return 1
  script:
    - apk add --no-cache make git
    - git fetch --tags origin
    - make package
    - mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
    - mv mender-monitor-*.tar.gz ${CI_PROJECT_DIR}/stage-artifacts
    - ls -lh ${CI_PROJECT_DIR}/stage-artifacts/
  artifacts:
    paths:
      - stage-artifacts

build:mender-gateway:package:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  needs:
    - init:workspace
  allow_failure: false
  before_script:
    # Early exit when building an integration version without mender-gateway
    - apt update && apt install -yyq xz-utils
    - xz -d workspace.tar.xz
    - tar -tf workspace.tar
        ./go/src/github.com/mendersoftware/mender-gateway  >/dev/null 2>/dev/null || exit 0
    # Restore workspace from init stage
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - tar -xf /tmp/workspace.tar
    # Move into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-gateway
