
include:
  - project: 'Northern.tech/Mender/mender-gateway'
    file: '.gitlab-ci-build-package.yml'
    ref: 'master'
  - project: 'Northern.tech/Mender/generate-delta-worker'
    file: '.gitlab-ci-build.yml'
    ref: 'master'

build:client:docker:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  only:
    variables:
      - $BUILD_CLIENT == "true"
  variables:
    DOCKER_BUILDKIT: 1
  needs:
    - init:workspace
  allow_failure: false
  image: docker
  services:
    - docker:dind
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt
    # Dependencies
    - apk --update add python3 py-pip curl jq bash git xz
    - wget https://raw.githubusercontent.com/mendersoftware/integration/master/extra/requirements.txt
    - pip3 install -r requirements.txt
    # Post job status
    - source ${CI_PROJECT_DIR}/build_revisions.env
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
    # Prepare workspace
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
  script:
    - mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
    # First build mender's repo Docker image
    - docker_url=$($WORKSPACE/integration/extra/release_tool.py --map-name docker mender-client-docker docker_url)
    - cd go/src/github.com/mendersoftware/mender
    - git submodule update --init
    - ./tests/build-docker -t $docker_url:pr
    - docker save $docker_url:pr -o ${CI_PROJECT_DIR}/stage-artifacts/mender-client-docker.tar
    # Then, if available, build integration's repo Docker image (Mender 2.7 and later)
    - if $($WORKSPACE/integration/extra/release_tool.py -l docker | egrep -q '^mender-client-docker-addons$'); then
    -   docker_url=$($WORKSPACE/integration/extra/release_tool.py --map-name docker mender-client-docker-addons docker_url)
    -   cd $WORKSPACE/integration/extra/mender-client-docker-addons
    -   docker build
        --build-arg MENDER_CLIENT_REV=$MENDER_REV
        --build-arg MENDER_CONNECT_REV=$MENDER_CONNECT_REV
        --build-arg MENDER_SETUP_REV=$MENDER_SETUP_REV
        --tag $docker_url:pr
        .
    -   mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
    -   docker save $docker_url:pr -o ${CI_PROJECT_DIR}/stage-artifacts/mender-client-docker-addons.tar
    - fi
    - echo "success" > /JOB_RESULT.txt
  after_script:
    - ls -lh stage-artifacts/
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    expire_in: 2w
    paths:
      - stage-artifacts/

build:servers:
  tags:
    - mender-qa-worker-generic-heavy
  stage: build
  only:
    variables:
      - $BUILD_SERVERS == "true"
      - $RUN_BACKEND_INTEGRATION_TESTS == "true"
      - $RUN_INTEGRATION_TESTS == "true"
  variables:
    DOCKER_BUILDKIT: 1
  needs:
    - init:workspace
  allow_failure: false
  image: docker
  services:
    - docker:dind
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt
    # Dependencies
    - apk --update add bash git make python3 py-pip curl jq xz
    - wget https://raw.githubusercontent.com/mendersoftware/integration/master/extra/requirements.txt
    - pip3 install -r requirements.txt
    # Post job status
    - source ${CI_PROJECT_DIR}/build_revisions.env
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
    # Prepare workspace
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
  script:
    - ${WORKSPACE}/mender-qa/scripts/servers-build.sh
    - echo "success" > /JOB_RESULT.txt
  after_script:
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - if [ "$(cat /JOB_RESULT.txt)" != "success" ]; then ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"; fi

    - mkdir -p stage-artifacts
    - for image in $(${CI_PROJECT_DIR}/../integration/extra/release_tool.py -l docker); do
    -   if ! echo $image | egrep -q 'mender-client|mender-qemu|mender-monitor|mender-gateway|generate-delta-worker'; then
    -     docker_url=$(${CI_PROJECT_DIR}/../integration/extra/release_tool.py --map-name docker $image docker_url)
    -     docker save $docker_url:pr -o stage-artifacts/${image}.tar
    -   fi
    - done

    - ls -lh stage-artifacts/
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    expire_in: 2w
    paths:
      - stage-artifacts/

build:mender-cli:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  only:
    variables:
      - $BUILD_SERVERS == "true"
      - $RUN_BACKEND_INTEGRATION_TESTS == "true"
      - $RUN_INTEGRATION_TESTS == "true"
  image: golang:1.18-alpine3.15
  needs:
    - init:workspace
  allow_failure: false
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt

    # Restore workspace from init stage
    - apk --update add xz
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz build_revisions.env /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
    - mv /tmp/build_revisions.env .
    # Export GOPATH
    - export GOPATH="$WORKSPACE/go"

    - apk --update add jq make curl git

    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

    # cd into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-cli
  script:
    - if grep -q build-multiplatform Makefile; then
        make build-multiplatform;
      else
        make build;
      fi
    - mkdir -p $CI_PROJECT_DIR/stage-artifacts
    - cp mender-cli* $CI_PROJECT_DIR/stage-artifacts

    # Always keep this at the end of the script stage
    - echo "success" > /JOB_RESULT.txt

  after_script:
    - ls -lh stage-artifacts/
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    paths:
      - stage-artifacts/

build:mender-artifact:
  tags:
    - mender-qa-worker-generic
  stage: build
  only:
    variables:
      - $BUILD_CLIENT == "true"
      - $RUN_BACKEND_INTEGRATION_TESTS == "true"
      - $RUN_INTEGRATION_TESTS == "true"
  variables:
    DOCKER_BUILDKIT: 1
  image: docker
  services:
    - docker:dind
  needs:
    - init:workspace
  allow_failure: false
  before_script:
    # Default value, will later be overwritten if successful
    - echo "failure" > /JOB_RESULT.txt

    # Check correct dind setup
    - docker version
    # Install dependencies
    - apk --update add bash curl git make jq xz
    # Restore workspace from init stage
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz build_revisions.env /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar
    - mv /tmp/build_revisions.env .

    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

    # cd into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-artifact
  script:
    - make build-natives-contained
    - mkdir -p $CI_PROJECT_DIR/stage-artifacts
    - cp mender-artifact-* $CI_PROJECT_DIR/stage-artifacts

    # Always keep this at the end of the script stage
    - echo "success" > /JOB_RESULT.txt

  after_script:
    - ls -lh stage-artifacts/
    # Post job status
    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"

  artifacts:
    expire_in: 2w
    paths:
      - stage-artifacts/

build:mender-monitor:package:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  image: alpine:3.12
  needs: []
  allow_failure: false
  before_script:
    - apk add --no-cache git openssh
    # Prepare SSH keys
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    # Clone monitor-client
    - git clone git@github.com:mendersoftware/monitor-client monitor-client
    - cd monitor-client
    - ( git fetch -u -f origin $MONITOR_CLIENT_REV:pr &&
          git checkout pr ||
          git checkout -f -b pr $MONITOR_CLIENT_REV
      ) || return 1
  script:
    - apk add --no-cache make git
    - git fetch --tags origin
    - make package
    - mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
    - mv mender-monitor-*.tar.gz ${CI_PROJECT_DIR}/stage-artifacts
    - ls -lh ${CI_PROJECT_DIR}/stage-artifacts/
  artifacts:
    paths:
      - stage-artifacts

build:mender-gateway:package:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  needs:
    - init:workspace
  allow_failure: false
  before_script:
    # Early exit when building an integration version without mender-gateway
    - apt update && apt install -yyq xz-utils
    - xz -d workspace.tar.xz
    - tar -tf workspace.tar
        ./go/src/github.com/mendersoftware/mender-gateway  >/dev/null 2>/dev/null || exit 0
    # Restore workspace from init stage
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar build_revisions.env /tmp
    - rm -rf ${WORKSPACE}
    - mkdir -p ${WORKSPACE}
    - cd ${WORKSPACE}
    - tar -xf /tmp/workspace.tar
    - mv /tmp/build_revisions.env .
    # Move into component path
    - cd ${WORKSPACE}/go/src/github.com/mendersoftware/mender-gateway

build:generate-delta-worker:docker:
  tags:
    - mender-qa-worker-generic-light
  stage: build
  variables:
    MULTIPLATFORM_PLATFORMS: "linux/amd64"
  rules:
    - if: $BUILD_SERVERS == "true" || $RUN_BACKEND_INTEGRATION_TESTS == "true" || $RUN_INTEGRATION_TESTS == "true"
  needs:
    - init:workspace
    - build:mender-artifact
  allow_failure: false
  before_script:
    # mender-qa specific before_script
    - apk --update --no-cache add bash curl aws-cli xz binutils python3
    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
    - mv workspace.tar.xz /tmp
    - mkdir -p "${WORKSPACE}"
    - cd "${WORKSPACE}"
    - xz -d /tmp/workspace.tar.xz
    - tar -xf /tmp/workspace.tar

    - if ! "${WORKSPACE}/integration/extra/release_tool.py" -l | grep -qF generate-delta-worker; then
        # Skip build on branches that don't include generate-delta-worker.
    -   exit 0
    - fi

    - repository=$(basename ${DOCKER_REPOSITORY})
    - cd "go/src/github.com/mendersoftware/$repository"
    - cp "${CI_PROJECT_DIR}/stage-artifacts/mender-artifact-linux" mender-artifact-amd64 # we're using multiplatform build
    - FORCE_DOCKER_BUILD_TAG=pr
    # build:generate-delta-worker:docker original before_script
    - if [[ "$MENDER_BINARY_DELTA_VERSION" == "latest" ]]; then MENDER_BINARY_DELTA_VERSION=master; fi
    - echo "MENDER_ARTIFACT_REV=$MENDER_ARTIFACT_REV MENDER_BINARY_DELTA_VERSION=$MENDER_BINARY_DELTA_VERSION"
    - export AWS_ACCESS_KEY_ID="$AWSRO_MENDER_BINARY_DELTA_AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWSRO_MENDER_BINARY_DELTA_AWS_SECRET_ACCESS_KEY"
    - aws s3 cp s3://mender-binaries/mender-binary-delta/$MENDER_BINARY_DELTA_VERSION/mender-binary-delta-$MENDER_BINARY_DELTA_VERSION.tar.xz .
    - xz -cd mender-binary-delta-$MENDER_BINARY_DELTA_VERSION.tar.xz | tar xvf -;
    - cp mender-binary-delta-$MENDER_BINARY_DELTA_VERSION/x86_64/mender-binary-delta-generator mender-binary-delta-generator-amd64
    - cp mender-binary-delta-$MENDER_BINARY_DELTA_VERSION/aarch64/mender-binary-delta-generator mender-binary-delta-generator-arm64
    - if [[ ! -f mender-artifact-amd64 ]]; then
        tmpdir=$(mktemp -d);
        wget "https://downloads.mender.io/repos/debian/pool/main/m/mender-artifact/mender-artifact_${MENDER_ARTIFACT_REV}-1%2Bdebian%2Bbullseye_amd64.deb" -O  ${tmpdir}/mender-artifact-amd64.deb;
        ar --output ${tmpdir} -xvf ${tmpdir}/mender-artifact-amd64.deb data.tar.xz;
        tar --directory ${tmpdir} -xvf ${tmpdir}/data.tar.xz ./usr/bin/mender-artifact;
        mv ${tmpdir}/usr/bin/mender-artifact mender-artifact-amd64;
        rm -rf ${tmpdir};
      fi
    - if [[ ! -f mender-artifact-arm64 ]]; then
        tmpdir=$(mktemp -d);
        wget "https://downloads.mender.io/repos/debian/pool/main/m/mender-artifact/mender-artifact_${MENDER_ARTIFACT_REV}-1%2Bdebian%2Bbullseye_arm64.deb" -O  ${tmpdir}/mender-artifact-arm64.deb;
        ar --output ${tmpdir} -xvf ${tmpdir}/mender-artifact-arm64.deb data.tar.xz;
        tar --directory ${tmpdir} -xvf ${tmpdir}/data.tar.xz ./usr/bin/mender-artifact;
        mv ${tmpdir}/usr/bin/mender-artifact mender-artifact-arm64;
        rm -rf ${tmpdir};
      fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_BUILD_TAG=${CI_COMMIT_REF_SLUG:-local}
    - if [ "${FORCE_DOCKER_BUILD_TAG}" != "" ]; then DOCKER_BUILD_TAG="${FORCE_DOCKER_BUILD_TAG}"; fi
    - export DOCKER_BUILD_SERVICE_IMAGE=${DOCKER_REPOSITORY}:${DOCKER_BUILD_TAG}
    - export DOCKER_PUBLISH_TAG=${CI_COMMIT_REF_NAME}
    - export DOCKER_PUBLISH_COMMIT_TAG=${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}
    - regctl image export ${GITLAB_REGISTRY_TAG} "${CI_PROJECT_DIR}/stage-artifacts/${repository}.tar --platform 'linux/amd64'
  artifacts:
    expire_in: 2w
    paths:
      - stage-artifacts/
