
mender-qa:success:
  tags:
    - mender-qa-worker-generic-light
  stage: .post
  dependencies: []
  when: on_success
  # Keep overhead low by using a small image with curl preinstalled.
  image: curlimages/curl-base
  before_script:
    - apk --update add jq
  script:
    - $CI_PROJECT_DIR/scripts/github_pull_request_status success "mender-qa pipeline passed" $CI_PIPELINE_URL ci/mender-qa

mender-qa:failure:
  tags:
    - mender-qa-worker-generic-light
  stage: .post
  dependencies: []
  when: on_failure
  # Keep overhead low by using a small image with curl preinstalled.
  image: curlimages/curl-base
  before_script:
    - apk --update add jq
  script:
    - $CI_PROJECT_DIR/scripts/github_pull_request_status failure "mender-qa pipeline failed" $CI_PIPELINE_URL ci/mender-qa


.coveralls:finish-build:
  tags:
    - mender-qa-worker-generic-light
  stage: .post
  dependencies: []
  # See https://docs.coveralls.io/parallel-build-webhook
  variables:
    COVERALLS_WEBHOOK_URL: "https://coveralls.io/webhook"
  image: curlimages/curl-base
  dependencies:
    - init:workspace
  before_script:
    - apk --update add git
    # Get mender source
    - tar xf ${CI_PROJECT_DIR}/workspace.tar.gz ./go/src/github.com/mendersoftware/${REPO_NAME}
    - mv go/src/github.com/mendersoftware/${REPO_NAME} ${CI_PROJECT_DIR}/${REPO_NAME}
    - cd ${CI_PROJECT_DIR}/${REPO_NAME}
  script:
    # Mark coverage report as done (mender-client).
    - 'curl -f ${COVERALLS_WEBHOOK_URL}?repo_token=${COVERALLS_TOKEN} -d "payload[build_num]=$(git rev-parse HEAD)&payload[status]=done"'

# Publish acceptance test coverage into coveralls when either:
# * running tests for a mender PR: MENDER_REV ~= /pull/XXX/head/
# * running nightly build: $NIGHTLY_BUILD == "true"
coverage:finish-build:mender-client:
  extends: .coveralls:finish-build
  only:
    variables:
      - $MENDER_REV =~ /pull\/.*\/head/
      - $NIGHTLY_BUILD == "true"
  variables:
      COVERALLS_TOKEN: ${MENDER_COVERALLS_TOKEN}
      REPO_NAME: "mender"

# Publish acceptance test coverage into coveralls when either:
# * running tests for a mender PR: MENDER_ARTIFACT_REV ~= /pull/XXX/head/
# * running nightly build: $NIGHTLY_BUILD == "true"
coverage:finish-build:mender-artifact:
  extends: .coveralls:finish-build
  only:
    variables:
      - $MENDER_ARTIFACT_REV =~ /pull\/.*\/head/
      - $NIGHTLY_BUILD == "true"
  variables:
      COVERALLS_TOKEN: ${MENDER_ARTIFACT_COVERALLS_TOKEN}
      REPO_NAME: "mender-artifact"

trigger:mantra:
  stage: .post
  inherit:
    variables: false
  trigger:
    branch: master
    project: Northern.tech/Mender/mantra
    strategy: depend
  rules:
    - if: $NIGHTLY_BUILD == "true"
      when: always
