.template:trigger:mender-convert:
  stage: trigger:images
  inherit:
    variables: false
  variables:
    MENDER_ARTIFACT_VERSION: $MENDER_ARTIFACT_REV
    MENDER_CLIENT_VERSION: $MENDER_REV
    MENDER_ADDON_CONNECT_VERSION: $MENDER_CONNECT_REV
    MENDER_ADDON_CONFIGURE_VERSION: $MONITOR_CLIENT_REV

    # Mode: "build and publish" or "build and test"
    TEST_MENDER_CONVERT: $TEST_MENDER_CONVERT
    PUBLISH_MENDER_CONVERT_AUTOMATIC: $PUBLISH_RELEASE_AUTOMATIC
  trigger:
    project: Northern.tech/Mender/mender-convert
    branch: $MENDER_CONVERT_REV
    strategy: depend


# mender-convert downloads mender-artifact from upstream, so the trigger(s) either
# need release_binary_tools:manual or release_binary_tools:automatic.
trigger:mender-convert:manual:
  needs:
    - job: trigger:mender-dist-packages
      artifacts: false
    - job: release_binary_tools:manual
      artifacts: false
  rules:
    - if: '$BUILD_MENDER_CONVERT == "true" && $PUBLISH_RELEASE_AUTOMATIC == "false"'
  extends: .template:trigger:mender-convert

trigger:mender-convert:automatic:
  needs:
    - job: trigger:mender-dist-packages
      artifacts: false
    - job: release_binary_tools:automatic
      artifacts: false
  rules:
    - if: '$BUILD_MENDER_CONVERT == "true" && $PUBLISH_RELEASE_AUTOMATIC == "true"'
  extends: .template:trigger:mender-convert
