.trigger_template:
  stage: trigger
  rules:
    # Disabled for the time being. See QA-322
    - when: never
    # - if: '$INTEGRATION_REV =~ /^[0-9]+\.[0-9]+\.[0-9]+(-build\d+)?$/'
    # # the following is to prevent an endless loop of qa pipelines caused by downstream pipelines
    # - if: '$CI_PIPELINE_SOURCE == "pipeline"'
    #   when: never

trigger:mender-convert:
  extends: .trigger_template
  variables:
    MENDER_ARTIFACT_VERSION: $MENDER_ARTIFACT_REV
    MENDER_CLIENT_VERSION: $MENDER_REV
    MENDER_ADDON_CONNECT_VERSION: $MENDER_CONNECT_REV
    # Obs! mender-configure-module is not part of the release (from release_tool eyes)
    # so it cannot be passed downstream to mender-convert.
    # It is not installed in our pre-converted images, so it doesn't really matter
    #MENDER_ADDON_CONFIGURE_VERSION
  trigger:
    project: Northern.tech/Mender/mender-convert
    branch: master
    strategy: depend
