trigger:mender-dist-packages:
  stage: trigger:packages
  inherit:
    variables: false
  needs: []
  rules:
    - if: $BUILD_MENDER_DIST_PACKAGES == "true"
  variables:
    # Trigger packaging for the Mender Client LTS release only; the rest are handled in their individual pipelines and release processes.
    # In other words Mender Client subcomponents from:
    # https://docs.mender.io/release-information/supported-releases#mender-client-subcomponents
    MENDER_VERSION: $MENDER_REV
    MENDER_CONNECT_VERSION: $MENDER_CONNECT_REV
    MENDER_MONITOR_VERSION: $MONITOR_CLIENT_REV
    MENDER_CONFIGURE_VERSION: $MENDER_CONFIGURE_MODULE_REV
    MENDER_FLASH_VERSION: $MENDER_FLASH_REV

    # Mode: "build and publish" or "build and test"
    TEST_MENDER_DIST_PACKAGES: $TEST_MENDER_DIST_PACKAGES
    PUBLISH_MENDER_DIST_PACKAGES_AUTOMATIC: $PUBLISH_RELEASE_AUTOMATIC
  trigger:
    project: Northern.tech/Mender/mender-dist-packages
    branch: $MENDER_DIST_PACKAGES_REV
    strategy: depend
