#!/bin/sh

set -e
set -x

"`dirname $0`"/../../build/tmp/sysroots/x86_64-linux/usr/bin/qemu-system-arm -nographic \
    -M vexpress-a9 \
    -m 1G \
    -kernel "`dirname $0`"/../../build/tmp/deploy/images/vexpress-qemu/u-boot.elf \
    -drive file=part.dat,if=sd,format=raw \
    -net nic \
    -net user,hostfwd=tcp::8822-:22 \
    "$@"
